### ISSUE TITLE
Dropbox-based command history for students

### ISSUE THREAD

**Issue by noamross** [dib-lab/2015-07-06-ucdavis#1]
The [last SWC debrief post](http://software-carpentry.org/blog/2015/06/instructor-debriefing-2015-06-09.html) mentioned a successful strategy of using Dropbox to keep a sync'd file of command history during the workshop, so that students can refer back to it during lessons.

For the R lessons, all that need to be done for this is to point the students to a Dropbox link of the current script file.  We just need to save frequently.

For shell/git lessons, you'll want to temporarily put something like this into your .bashrc so that you save a history file as you go:

```
shopt -s histappend # append to existing history
export PROMPT_COMMAND='history -a'  #record to history file immediately for every line
$HISTFILE=~/Dropbox/whatever/command_history.txt  #put 
```

Then we can point the students to the Dropbox link, which they can view in the browser and refresh as they need it.

**Comment by ctb** [comment]
cc @tracykteal
