### ISSUE TITLE
Pre-workshop survey

### ISSUE THREAD

**Issue by noamross** [dib-lab/2015-07-06-ucdavis#4]
I see SWC has a standardized survey for skill assessment: http://software-carpentry.org/workshops/assess/pre-learner.html

However, if the chosen curriculum is slightly different (adding reproducible documents, removing SQL and unit testing), can/should we modify the survey?

cc: @gvwilson @chendaniely

**Comment by gvwilson** [comment]
Hoo boy... the short answer is "yes", but the longer answer is, "but 
then how do we integrate all the data"?  Adding/removing items in a 
Google Forms survey (or in Surveymonkey) changes the order of the output 
items, which is a pain but solvable; figuring out which questions 
overlap with which, at scale, is more of a pain...
