### ISSUE TITLE
Question time?

### ISSUE THREAD

**Issue by noamross** [dib-lab/2015-07-06-ucdavis#5]
Just an idea, which I may ping the SWC [Discuss] list about:

Has anyone ever set aside a period for open "question time" at an SWC/DC workshop? The idea would be for people to be able to ask specific questions along the lines of "how would you [do this thing related to my work]?" I think something like this would be useful for helping people connect the workshop material to their current problems.  The key would be answering the questions in a way that emphasizes _how you would figure out the answer_ as opposed to _what the answer is_, in order to model the discovery process.  Thoughts?

pinging @ctb because it appears he doesn't watch this repo's alerts ;)

**Comment by ctb** [comment]
I think it's a good idea. When are you thinking?

(And thanks for the pointer on the alerts. Subscribed :)

**Comment by eastonwhite** [comment]
I think it's a good idea. I also found it extremely helpful to have participants try to meet up several weeks after the workshop has concluded. We talked about parts of the workshop that were unclear, troubleshooted, and discussed general daily workflow using these tools.

**Comment by ctb** [comment]
Shall we schedule something for the 29th?  I can reserve a room, or we can
do it over in the library, or something.

**Comment by noamross** [comment]
It would be good to hold this follow-up to the SWC workshop at a D-RUG meeting.  We meet Tuesdays 10-12, so could we do it then on July 28? Or perhaps the D-RUG admins can join us for something on the 29th.  @Myfanwy and @michaellevy, are either of you free on the 29th?

**Comment by ctb** [comment]
I have a defense that will probably go until ~1pm on that Tuesday :(.

**Comment by michaellevy** [comment]
I am out of town that whole week.

> It would be good to hold this follow-up to the SWC workshop at a D-RUG meeting. We meet Tuesdays 10-12, so could we do it then on July 28? Or perhaps the D-RUG admins can join us for something on the 29th. @Myfanwy and @michaellevy, are either of you free on the 29th?

**Comment by Myfanwy** [comment]
I'm free then, but it sounds like we should try another week...

On Mon, Jul 6, 2015 at 6:20 PM, Michael Levy notifications@github.com
wrote:

> I am out of town that whole week.
> 
> It would be good to hold this follow-up to the SWC workshop at a D-RUG
> meeting. We meet Tuesdays 10-12, so could we do it then on July 28? Or
> perhaps the D-RUG admins can join us for something on the 29th. @Myfanwy
> https://github.com/Myfanwy and @michaellevy
> https://github.com/michaellevy, are either of you free on the 29th?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dib-lab/2015-07-06-ucdavis/issues/5#issuecomment-119040741
> .

## 

Myfanwy Johnston
Ph.D Candidate, Animal Behavior
University of California at Davis
Biotelemetry Lab

**Comment by noamross** [comment]
What's everyone's availability 10-12 on the Tuesdays of the 14th and 21st?
I should be available for either.  Ideally we'd have @ctb, at least one of
me and @erwhite1 and at least one of the D-RUG leaders.

**Comment by eastonwhite** [comment]
I am free either of those days at that time

**Comment by Myfanwy** [comment]
I'm free the 21st, but I have a dentist appointment on the 14th during that
time :(

On Mon, Jul 6, 2015 at 8:33 PM, Easton R. White notifications@github.com
wrote:

> I am free either of those days at that time
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dib-lab/2015-07-06-ucdavis/issues/5#issuecomment-119062310
> .

## 

Myfanwy Johnston
Ph.D Candidate, Animal Behavior
University of California at Davis
Biotelemetry Lab

**Comment by michaellevy** [comment]
I'm available on the 14th and 21st.

**Comment by noamross** [comment]
Let's do it 10-12 on the 21st.  I'll let the workshop participants know.

**Comment by tracykteal** [comment]
I'm available then too, so I'll plan to be there. Maybe we could just update this issue with the location when it's decided?

**Comment by noamross** [comment]
Location: 2124 Wickson Hall
