### ISSUE TITLE
Recruit helpers

### ISSUE THREAD

**Issue by noamross** [dib-lab/2015-07-06-ucdavis#6]
I can ping the D-RUG crew for helpers. @ctb: Are we expecting any from dib-lab?

**Comment by ctb** [comment]
On Mon, Jun 22, 2015 at 05:49:54PM -0700, Noam Ross wrote:

> I can ping the D-RUG crew for helpers. @ctb: Are we expecting any from dib-lab?

Not at this time. I haven't really asked but we are few in number at the
moment :)
